# Generated by Django 3.1.4 on 2020-12-15 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Filename'),
        ),
    ]
