# Generated by Django 3.1.3 on 2020-11-16 06:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20201115_1910'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Slug')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('username', models.CharField(max_length=90, verbose_name='User name')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('date_sent', models.DateTimeField(blank=True, null=True, verbose_name='Date sent')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.book', verbose_name='Book')),
            ],
            options={
                'verbose_name': 'Lead',
                'verbose_name_plural': 'Leads',
                'ordering': ['-date_sent'],
            },
        ),
    ]
