# Generated by Django 3.1.3 on 2020-11-23 16:05

import cms.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_auto_20201123_1250'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['order'], 'verbose_name': 'Book', 'verbose_name_plural': 'Books'},
        ),
        migrations.AlterModelOptions(
            name='lead',
            options={'ordering': ('order', '-date_sent'), 'verbose_name': 'Lead', 'verbose_name_plural': 'Leads'},
        ),
        migrations.AlterField(
            model_name='book',
            name='order',
            field=cms.fields.OrderField(blank=True, verbose_name='Order #'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='order',
            field=cms.fields.OrderField(blank=True, verbose_name='Order #'),
        ),
    ]
